### ISSUE TITLE
Generated project does not work when updating `cozy-ui` dependency

### ISSUE THREAD

**Issue by klehelley** [CPatchane/create-cozy-app#1238]
**Summary**

When creating a brand new project with `create-react-app`, upgrading `cozy-ui` to the latest version results in the project not being buildable.

**How to reproduce**

1. Create a new project: `yarn create cozy-app demo-cozy-ui-issue && cd demo-cozy-ui-issue`
2. Upgrade the `cozy-ui` dependency to a very recent version: `yarn add cozy-ui@20.16.5`
3. Either build the project `yarn build` or start the development server `yarn start`; an error is shown and the process fails

**Error message**

```
    ERROR in ./src/styles/index.styl
    Module build failed (from ./node_modules/mini-css-extract-plugin/dist/loader.js):
    ModuleBuildError: Module build failed (from ./node_modules/stylus-loader/index.js):
    Error: Workspace/cozy/demo-cozy-ui-issue/node_modules/cozy-ui/stylus/cozy-ui/build.styl:13:10
        9| \*------------------------------------*/
       10| @require '../settings/*'
       11| @require '../tools/*'
       12| @require '../generic/animations'
       13| @require '../../node_modules/normalize.css/normalize'
    ----------------^
       14| @require '../elements/*'
       15| @require '../objects/*'
       16| @require '../components/*'
    
    failed to locate @require file ../../node_modules/normalize.css/normalize.styl
    
        at CachedPathEvaluator.visitImport (Workspace/cozy/demo-cozy-ui-issue/node_modules/stylus-loader/lib/evaluator.js:157:21)
        at CachedPathEvaluator.Visitor.visit (Workspace/cozy/demo-cozy-ui-issue/node_modules/stylus/lib/visitor/index.js:28:40)
        at CachedPathEvaluator.Evaluator.visit (Workspace/cozy/demo-cozy-ui-issue/node_modules/stylus/lib/visitor/evaluator.js:160:18)
        at CachedPathEvaluator.Evaluator.visitBlock (Workspace/cozy/demo-cozy-ui-issue/node_modules/stylus/lib/visitor/evaluator.js:720:39)
        at CachedPathEvaluator.Visitor.visit (Workspace/cozy/demo-cozy-ui-issue/node_modules/stylus/lib/visitor/index.js:28:40)
        at CachedPathEvaluator.Evaluator.visit (Workspace/cozy/demo-cozy-ui-issue/node_modules/stylus/lib/visitor/evaluator.js:160:18)
        at CachedPathEvaluator.importFile (Workspace/cozy/demo-cozy-ui-issue/node_modules/stylus-loader/lib/evaluator.js:84:18)
        at CachedPathEvaluator.visitImport (Workspace/cozy/demo-cozy-ui-issue/node_modules/stylus-loader/lib/evaluator.js:162:27)
        at CachedPathEvaluator.Visitor.visit (Workspace/cozy/demo-cozy-ui-issue/node_modules/stylus/lib/visitor/index.js:28:40)
        at CachedPathEvaluator.Evaluator.visit (Workspace/cozy/demo-cozy-ui-issue/node_modules/stylus/lib/visitor/evaluator.js:160:18)
        at CachedPathEvaluator.Evaluator.visitRoot (Workspace/cozy/demo-cozy-ui-issue/node_modules/stylus/lib/visitor/evaluator.js:707:27)
        at CachedPathEvaluator.Visitor.visit (Workspace/cozy/demo-cozy-ui-issue/node_modules/stylus/lib/visitor/index.js:28:40)
        at CachedPathEvaluator.Evaluator.visit (Workspace/cozy/demo-cozy-ui-issue/node_modules/stylus/lib/visitor/evaluator.js:160:18)
        at CachedPathEvaluator.Evaluator.evaluate (Workspace/cozy/demo-cozy-ui-issue/node_modules/stylus/lib/visitor/evaluator.js:247:15)
        at Renderer.render (Workspace/cozy/demo-cozy-ui-issue/node_modules/stylus/lib/renderer.js:86:26)
        at Workspace/cozy/demo-cozy-ui-issue/node_modules/stylus-loader/index.js:167:12
        at runLoaders (Workspace/cozy/demo-cozy-ui-issue/node_modules/webpack/lib/NormalModule.js:301:20)
        at Workspace/cozy/demo-cozy-ui-issue/node_modules/loader-runner/lib/LoaderRunner.js:367:11
        at Workspace/cozy/demo-cozy-ui-issue/node_modules/loader-runner/lib/LoaderRunner.js:233:18
        at context.callback (Workspace/cozy/demo-cozy-ui-issue/node_modules/loader-runner/lib/LoaderRunner.js:111:13)
        at Workspace/cozy/demo-cozy-ui-issue/node_modules/stylus-loader/index.js:169:11
        at Renderer.render (Workspace/cozy/demo-cozy-ui-issue/node_modules/stylus/lib/renderer.js:107:12)
        at Workspace/cozy/demo-cozy-ui-issue/node_modules/stylus-loader/index.js:167:12
        at tryCatchReject (Workspace/cozy/demo-cozy-ui-issue/node_modules/when/lib/makePromise.js:840:30)
        at runContinuation1 (Workspace/cozy/demo-cozy-ui-issue/node_modules/when/lib/makePromise.js:799:4)
        at Fulfilled.when (Workspace/cozy/demo-cozy-ui-issue/node_modules/when/lib/makePromise.js:590:4)
        at Pending.run (Workspace/cozy/demo-cozy-ui-issue/node_modules/when/lib/makePromise.js:481:13)
        at Scheduler._drain (Workspace/cozy/demo-cozy-ui-issue/node_modules/when/lib/Scheduler.js:62:19)
        at Scheduler.drain (Workspace/cozy/demo-cozy-ui-issue/node_modules/when/lib/Scheduler.js:27:9)
        at process._tickCallback (internal/process/next_tick.js:61:11)
     @ ./src/targets/browser/index.jsx 2:0-16
     @ multi ./node_modules/babel-polyfill/lib/index.js ./node_modules/cozy-scripts/utils/reactExposer.js ./src/targets/browser/index.jsx
```

**Additional information**

I came across the issue after noticing that the default `cozy-ui` dependency of the generated project was quite old, and I wanted to use the `Card` component in my project (I just noticed that that component is actually _a lot_ more recent that I thought). So I thought "Let's just bump the version of the dependency to the latest available, nothing too bad should happen..." Famous last words. :laughing: 

More seriously, the issue seems to have appeared following [PR 833 in cozy/cozy-ui](https://github.com/cozy/cozy-ui/pull/833) as using the following release (18.15.0) in the generated project shows the error above, but the previous version (18.14.0) does not.

I assume `cozy-ui` works as intended, hence why I am filing an issue here. I do not have enough experience with Webpack to know with certainty whether it is the case though.

**Comment by Crash--** [comment]
Thanks for reporting this issue. We will look at it pretty soon. 

I think this is because we didn't publish the current master of this repo... 

Can you try to add an alias : 
```
alias : {
    'cozy-ui/react': 'cozy-ui/transpiled/react'
}
```

In the `module ` object here: https://github.com/CPatchane/create-cozy-app/blob/v1.12.x/packages/cozy-scripts/config/webpack.config.react.js#L14

**Comment by klehelley** [comment]
Sorry to leave you waiting, there's been a big shift in priorities here for the last couple of weeks. I should hopefully be able to have some time dedicated to Cozy app development by the end of the week.

**Comment by CPatchane** [comment]
Hi @klehelley, thanks for reporting this issue and sorry for my late reply, but I wanted to fix some issues on the current unreleased version of CCA before and we were working on a v2 of this tool. Good news, this new version just released with all dependencies up to date.
Could you try again with the v2? Just doing `yarn create cozy-app <myapp>` should use directly the most recent version of CCA.

**Comment by klehelley** [comment]
Hi @CPatchane. I have tried to reproduce the issue with the latest version of `create-cozy-app` and it works well, with `cozy-ui` set at a more recent version than the one I was trying to use when I stumbled upon the issue. Thanks!
