### ISSUE TITLE
Watch crashes on module not found

### ISSUE THREAD

**Issue by ptbrowne** [CPatchane/create-cozy-app#160]
```
Error: ModuleNotFoundError: Module not found: Error: Can't resolve 'assets/icons/icon-filter' in '/Users/pbrowne/code/cozy/sante/src/components/AccountSwitch'
```

makes the watcher crash. Expected behavior would be to continue watching.

Stack trace:

```
Error: ModuleNotFoundError: Module not found: Error: Can't resolve 'assets/icons/icon-filter' in '/Users/pbrowne/code/cozy/sante/src/components/AccountSwitch'
    at Watching.compiler.watch [as handler] (/Users/pbrowne/code/cozy/sante/node_modules/cozy-scripts/scripts/watch.js:19:13)
    at Watching._done (/Users/pbrowne/code/cozy/sante/node_modules/webpack/lib/Compiler.js:100:9)
    at onCompiled (/Users/pbrowne/code/cozy/sante/node_modules/webpack/lib/Compiler.js:50:25)
    at applyPluginsParallel.err (/Users/pbrowne/code/cozy/sante/node_modules/webpack/lib/Compiler.js:504:20)
    at /Users/pbrowne/code/cozy/sante/node_modules/tapable/lib/Tapable.js:285:11
    at _addModuleChain (/Users/pbrowne/code/cozy/sante/node_modules/webpack/lib/Compilation.js:498:12)
    at processModuleDependencies.err (/Users/pbrowne/code/cozy/sante/node_modules/webpack/lib/Compilation.js:474:15)
    at finalCallbackAddModuleDependencies (/Users/pbrowne/code/cozy/sante/node_modules/webpack/lib/Compilation.js:375:12)
    at /Users/pbrowne/code/cozy/sante/node_modules/webpack/node_modules/async/dist/async.js:473:16
    at iteratorCallback (/Users/pbrowne/code/cozy/sante/node_modules/webpack/node_modules/async/dist/async.js:1048:13)
    at /Users/pbrowne/code/cozy/sante/node_modules/webpack/node_modules/async/dist/async.js:958:16
    at finalCallbackAddModuleDependencies (/Users/pbrowne/code/cozy/sante/node_modules/webpack/lib/Compilation.js:375:12)
    at /Users/pbrowne/code/cozy/sante/node_modules/webpack/node_modules/async/dist/async.js:473:16
    at iteratorCallback (/Users/pbrowne/code/cozy/sante/node_modules/webpack/node_modules/async/dist/async.js:1048:13)
    at /Users/pbrowne/code/cozy/sante/node_modules/webpack/node_modules/async/dist/async.js:958:16
    at finalCallbackAddModuleDependencies (/Users/pbrowne/code/cozy/sante/node_modules/webpack/lib/Compilation.js:375:12)
```

**Comment by CPatchane** [comment]
See #193

**Comment by CPatchane** [comment]
PR merged. Thanks @ptbrowne 👍
