### ISSUE TITLE
yarn add --exact cozy-scripts has failed: EROFS: read-only file system, symlink

### ISSUE THREAD

**Issue by gcoter** [CPatchane/create-cozy-app#408]
Hi,

I ran the following command to intialize a new version of the cozy-music app:

`yarn create cozy-app cozy-music --vue`

I work on Ubuntu 16.04 LTS and I have installed:

- node v8.10.0
- yarn 1.5.1

Here are the logs:

```
yarn create v1.5.1
[1/4] Resolving packages...
[2/4] Fetching packages...
[3/4] Linking dependencies...
[4/4] Building fresh packages...
success Installed "create-cozy-app@0.5.8" with binaries:
      - create-cozy-app
[#####################################] 37/37

                                                     %@

     ,#@#W@@p   e@8W@@M,   @@@@@#@@b'@@      #@      @b    ;@#WW@M,
    6@C       ,@#     7$k       ##`  '@@    {$`      $b   @#     "Sk
    $$        @$~      @$     ;@^     '@k  {@^       $b  |$b      @$
    @@        !$b      S@   ,@#        ^Sk;$b        $b  |$b      @$
     @@w,,,#k  "$k,,,e@W   #@Q,,,,,     "$@C   &@k   $b   7@k,,,;@#`
       `^^`       ^^^`     ````````     ;$b    `^`   ``      `^^`
                                       ;$b


Let's create the Cozy Application in /media/sf_projects/cozy-music


✖ An error occured during cozy-music initialisation. Aborting.
yarn add --exact cozy-scripts has failed.

Cleaning remaining generated elements
Deleting generated files/folders from /media/sf_projects/cozy-music
	- node_modules deleted.
	- package.json deleted.
	- yarn-error.log deleted.

cozy-music/ empty folder deleted.
error An unexpected error occurred: "Command failed.
Exit code: 1
Command: /home/gcoter/.yarn/bin/create-cozy-app
Arguments: cozy-music --vue
Directory: /media/sf_projects
Output:
".
info If you think this is a bug, please open a bug report with the information provided in "/home/gcoter/.config/yarn/global/yarn-error.log".
info Visit https://yarnpkg.com/en/docs/cli/create for documentation about this command.
```

At the end of the "yarn-error.log" mentioned above, there are some additional logs:

```
Trace: 
  Error: Command failed.
  Exit code: 1
  Command: /home/gcoter/.yarn/bin/create-cozy-app
  Arguments: cozy-music --vue
  Directory: /media/sf_projects
  Output:
  
      at ProcessTermError.MessageError (/usr/share/yarn/lib/cli.js:186:110)
      at new ProcessTermError (/usr/share/yarn/lib/cli.js:226:113)
      at ChildProcess.<anonymous> (/usr/share/yarn/lib/cli.js:30281:17)
      at emitTwo (events.js:126:13)
      at ChildProcess.emit (events.js:214:7)
      at maybeClose (internal/child_process.js:925:16)
      at Process.ChildProcess._handle.onexit (internal/child_process.js:209:5)
```

How can I solve this issue?

**Comment by CPatchane** [comment]
Hi @gcoter, thanks for opening this issue. I did have some issues with the vue template from the deployed npm package. But I just published a new release at the same time of your issue to fix that, could you try again? It should be good now :)

**Comment by gcoter** [comment]
Hi @CPatchane, thank you for your quick response. I tried again and unfortunately I got the same error :(

**Comment by CPatchane** [comment]
Hum, interesting. What do you have when you add the option `--verbose`? You should have more logs.
I will add the version of cozy-scripts used in the logs, it could be better for debugging in the future.

**Comment by gcoter** [comment]
I ran the command with `--verbose`, here are the logs:

```
yarn create v1.5.1
[1/4] Resolving packages...
[2/4] Fetching packages...
[3/4] Linking dependencies...
[4/4] Building fresh packages...
success Installed "create-cozy-app@0.5.9" with binaries:
      - create-cozy-app
[#####################################] 37/37

                                                     %@

     ,#@#W@@p   e@8W@@M,   @@@@@#@@b'@@      #@      @b    ;@#WW@M,
    6@C       ,@#     7$k       ##`  '@@    {$`      $b   @#     "Sk
    $$        @$~      @$     ;@^     '@k  {@^       $b  |$b      @$
    @@        !$b      S@   ,@#        ^Sk;$b        $b  |$b      @$
     @@w,,,#k  "$k,,,e@W   #@Q,,,,,     "$@C   &@k   $b   7@k,,,;@#`
       `^^`       ^^^`     ````````     ;$b    `^`   ``      `^^`
                                       ;$b


Let's create the Cozy Application in /media/sf_projects/cozy-music


Installing cozy-scripts... (may take a while)
yarn add v1.5.1
warning package.json: No license field
info No lockfile found.
warning cozy-music: No license field
[1/4] Resolving packages...
[2/4] Fetching packages...
info fsevents@1.1.3: The platform "linux" is incompatible with this module.
info "fsevents@1.1.3" is an optional dependency and failed compatibility check. Excluding it from installation.
[3/4] Linking dependencies...
error An unexpected error occurred: "EROFS: read-only file system, symlink '../jsesc/bin/jsesc' -> '/media/sf_projects/cozy-music/node_modules/@babel/generator/node_modules/.bin/jsesc'".
info If you think this is a bug, please open a bug report with the information provided in "/media/sf_projects/cozy-music/yarn-error.log".
info Visit https://yarnpkg.com/en/docs/cli/add for documentation about this command.
yarn add --exact cozy-scripts has failed.

Cleaning remaining generated elements
Deleting generated files/folders from /media/sf_projects/cozy-music
	- node_modules deleted.
	- package.json deleted.
	- yarn-error.log deleted.

cozy-music/ empty folder deleted.
error An unexpected error occurred: "Command failed.
Exit code: 1
Command: /home/gcoter/.yarn/bin/create-cozy-app
Arguments: cozy-music --vue --verbose
Directory: /media/sf_projects
Output:
".
info If you think this is a bug, please open a bug report with the information provided in "/home/gcoter/.config/yarn/global/yarn-error.log".
info Visit https://yarnpkg.com/en/docs/cli/create for documentation about this command.

```

**Comment by gcoter** [comment]
Apparently, I am not the first one to get this kind of error : https://github.com/yarnpkg/yarn/issues/2983

**Comment by gcoter** [comment]
It worked! I simply ran the command in my home folder instead of the shared folder.

**Comment by CPatchane** [comment]
Oh good to know that and thanks for this solution. Did you try it? The `yarn` issue said that you have to [allow symlinks for VirtualBox guests](https://stackoverflow.com/a/28674584) and then rerun the command. It could be good to know if it solved your first issue.

**Comment by CPatchane** [comment]
No replies anymore. I close this issue, the solution seems to be above. We will reopen it if necessary.
